### ISSUE TITLE
bug(angular-output-target): events fire twice

### ISSUE THREAD

**Issue by razvangeangu** [ionic-team/stencil-ds-output-targets#81]
Since the events are added to the outputs array - there's no need to create an observable listener anymore to bubble the events. Instead - to keep the outputs array and the types, `fromEvent` can be replaced with an empty `EventEmitter` in the angular proxy utils.

```diff
export const proxyOutputs = (instance: any, el: any, events: string[]) => {
--  events.forEach((eventName) => (instance[eventName] = fromEvent(el, eventName)));
++  events.forEach((eventName) => (instance[eventName] = new EventEmitter()));
};
```

**Comment by jeserkin** [comment]
This needs to be a hotfix thou IMO

**Comment by dennispidun** [comment]
This resolved the issue. Thanks @razvangeangu! 

@jthoms1 please confirm that this pull-request can be merged...I need this to be part of the output-target for angular. Thank you.

**Comment by khronos90** [comment]
This is happening with both Angular 9 and Angular 10, and renders the output completely inusable. Is there any real work around for it? Changing directly the output doesn't make any sense in a CI/CD environment, since it will be regenerated each time the core library is built.

**Comment by razvangeangu** [comment]
The PR should resolve the issue. Alternatively, you may run a custom output target in your own repository or a postbuild script to resolve this issue.

```ts
/**
 * angular-output-target-fix.ts
 *
 * @author @razvangeangu
 */

import { BuildCtx, CompilerCtx, Config, OutputTargetCustom } from '@stencil/core/internal';
import fs from 'fs';
import path from 'path';

const runAngularOutputTargetFix = async (outputTarget: IAngularOutputTarget) => {
  const directivesUtilsPath = path.resolve(__dirname, outputTarget.directivesUtilsFile);

  let directivesUtilsString = await fs.promises.readFile(directivesUtilsPath, { encoding: 'utf-8' });
  directivesUtilsString = directivesUtilsString.replace(
    "import { fromEvent } from 'rxjs';",
    "import { EventEmitter } from '@angular/core';",
  );
  directivesUtilsString = directivesUtilsString.replace(
    'instance[eventName] = fromEvent(el, eventName)',
    'instance[eventName] = new EventEmitter()',
  );

  await fs.promises.writeFile(directivesUtilsPath, directivesUtilsString);
};

interface IAngularOutputTarget {
  directivesUtilsFile: string;
}

export const angularOutputTargetFix = async (
  outputTarget: IAngularOutputTarget,
): Promise<OutputTargetCustom> => ({
  type: 'custom',
  name: 'angular-library-fix',
  generator: async (_config: Config, compilerCtx: CompilerCtx, buildCtx: BuildCtx) => {
    const timespan = buildCtx.createTimeSpan('generate angular proxy utils fix started', true);

    await new Promise(resolve => {
      compilerCtx.events.on('buildLog', log => {
        if (log.messages.findIndex(elm => elm.includes('generate angular-library finished')) !== -1) {
          resolve();
        }
      });
    });

    compilerCtx.events.on('buildLog', log => {
      if (
        log.messages.findIndex(elm => elm.includes('build finished, watching for changes...')) !== -1
      ) {
        runAngularOutputTargetFix(outputTarget);
      }
    });

    await runAngularOutputTargetFix(outputTarget);

    timespan.finish('generate angular proxy utiils fix finished');
  },
});
```

```ts
/**
 * stencil.config.ts
 *
 * @author @razvangeangu
 */

import { angularOutputTarget } from "@stencil/angular-output-target";
import { Config } from "@stencil/core";
import { angularOutputTargetFix } from "./angular-output-target-fix";

export const config: Config = {
  outputTargets: [
    angularOutputTarget({
      componentCorePackage: "@ionic/components",
      directivesProxyFile:
        "../ionic-components-angular/src/directives/proxies.ts",
    }),
    angularOutputTargetFix({
      directivesUtilsFile:
        "../ionic-components-angular/src/directives/angular-component-lib/utils.ts",
    }),
  ],
};
```

**Comment by JCofman** [comment]
Hi @razvangeangu 

thanks a lot for your fix :) I needed to edit the code of `angularOutputTargetFix` to just return `OutputTargetCustom` instead of a `Promise<OutputTargetCustom>`

**Comment by nioe** [comment]
@razvangeangu I saw that you closed your [PR](https://github.com/ionic-team/stencil-ds-output-targets/pull/82) because your fix raised other issues... Are there any plans to create another fix for this bug?

**Comment by razvangeangu** [comment]
I'm open to other ideas @nioe

**Comment by bellindj** [comment]
@razvangeangu thank you for the solution. It appears to be working for us to both remove the double event emission but also doesn't appear to change the output type. We still get a CustomEvent. On 0.0.5.

**Comment by razvangeangu** [comment]
The output would be `CustomEvent` regardless of this solution. Previous versions were declaring this type anyway, the feature was just adding the `T` type in `CustomEvent<T>`

**Comment by jeserkin** [comment]
@razvangeangu just to clarify, does version 0.0.5 come already with a fix or it wasn't released officially yet?

**Comment by razvangeangu** [comment]
use 0.0.5 with the script from above

> @razvangeangu just to clarify, does version 0.0.5 come already with a fix or it wasn't released officially yet?

**Comment by willmartian** [comment]
Hi all, a fix for this issue is now available in `v0.2.1`, from #202. Let me know if you continue to see issues with this. Thanks for your patience! The Stencil team has some forthcoming documentation changes and bug fixes that should make the Angular output target a breeze to use.
